import { promises as fsp } from "node:fs"
import { join } from "node:path"

import { logRuntimeEvent, type RunManifest } from "./manifest.ts"

export type DockerfileResult = {
  /** Dockerfile path relative to the worktree cwd — pass as `-f` to `docker
   *  build`. We always emit a concrete path so the build context is cwd and
   *  the file location is decoupled from the default lookup rules. */
  path: string
  /** Absolute path to the Dockerfile on disk. */
  absolutePath: string
  /** Whether we wrote the file or used an existing one. */
  source: "user" | "generated"
  /** Resolved contents (for logging / display). */
  content: string
  /** Image tag we'll build as — stable for a given manifest so rebuilds
   *  reuse Docker's layer cache. Callers pass this to `docker run`. */
  imageTag: string
}

const CACHE_DIR = ".ai-coder"
const CACHE_FILE = "Dockerfile"

// Contract: if the user has Dockerfile at the worktree root, use it as-is —
// they took ownership. If `.ai-coder/Dockerfile` exists, use it — they may
// have edited our generated one. Otherwise generate fresh into .ai-coder/.
//
// `.ai-coder/` should be gitignored; we don't manage that for the user.
export async function generateDockerfile(
  manifest: RunManifest
): Promise<DockerfileResult> {
  const cwd = manifest.cwd
  const imageTag = buildImageTag(cwd)

  // 1. User-authored Dockerfile at the root wins.
  const rootDockerfile = join(cwd, "Dockerfile")
  if (await exists(rootDockerfile)) {
    const content = await fsp.readFile(rootDockerfile, "utf8")
    logRuntimeEvent("dockerfile.cache.hit", { path: "Dockerfile", source: "user" })
    return {
      path: "Dockerfile",
      absolutePath: rootDockerfile,
      source: "user",
      content,
      imageTag,
    }
  }

  // 2. `.ai-coder/Dockerfile` — either ours from a previous run, or edited.
  const cachedPath = join(cwd, CACHE_DIR, CACHE_FILE)
  const cached = await readIfExists(cachedPath)

  // 3. Generate fresh content, diff against cache. Only rewrite when it
  //    differs so we don't churn mtimes (Docker invalidates cache on mtime).
  const content = renderDockerfile(manifest)
  if (cached === content) {
    logRuntimeEvent("dockerfile.cache.hit", {
      path: `${CACHE_DIR}/${CACHE_FILE}`,
      source: "generated",
    })
    return {
      path: `${CACHE_DIR}/${CACHE_FILE}`,
      absolutePath: cachedPath,
      source: "generated",
      content,
      imageTag,
    }
  }

  await fsp.mkdir(join(cwd, CACHE_DIR), { recursive: true })
  await fsp.writeFile(cachedPath, content, "utf8")
  logRuntimeEvent("dockerfile.generate", {
    cwd,
    stack: manifest.stack,
    bytes: content.length,
  })
  return {
    path: `${CACHE_DIR}/${CACHE_FILE}`,
    absolutePath: cachedPath,
    source: "generated",
    content,
    imageTag,
  }
}

function renderDockerfile(manifest: RunManifest): string {
  switch (manifest.stack) {
    case "node":
    case "bun":
      return renderNode(manifest)
    case "python":
      return renderPython(manifest)
    case "static":
      return renderStatic(manifest)
    default:
      // Custom/unknown stacks: minimal generic template. The user should
      // author their own Dockerfile at the worktree root if this doesn't fit.
      return renderGeneric(manifest)
  }
}

function renderNode(manifest: RunManifest): string {
  const build = manifest.build?.trim()
  const start = escapeShell(manifest.start)
  const isBun = manifest.stack === "bun"
  const base = isBun ? "oven/bun:1" : "node:22-alpine"
  const installBlock = isBun
    ? "RUN bun install --frozen-lockfile || bun install"
    : [
        "RUN \\",
        "  if [ -f package-lock.json ]; then npm ci; \\",
        "  elif [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \\",
        "  elif [ -f yarn.lock ]; then corepack enable && yarn install --frozen-lockfile; \\",
        "  else npm install; fi",
      ].join("\n")

  return [
    "# Generated by ai-coder — edit .ai-coder/Dockerfile to customize.",
    "# Commit Dockerfile at the repo root to take full ownership (we won't overwrite it).",
    "",
    `FROM ${base}`,
    "WORKDIR /app",
    "",
    "# Dependencies first for cache-friendly layers.",
    isBun
      ? "COPY package.json bun.lock* bun.lockb* ./"
      : "COPY package*.json pnpm-lock.yaml* yarn.lock* ./",
    installBlock,
    "",
    "# App source.",
    "COPY . .",
    "",
    ...(build ? [`RUN ${build}`, ""] : []),
    "ENV PORT=3000",
    "EXPOSE 3000",
    `CMD ["sh", "-c", "${start}"]`,
    "",
  ].join("\n")
}

function renderPython(manifest: RunManifest): string {
  const start = escapeShell(manifest.start)
  const build = manifest.build?.trim()
  return [
    "# Generated by ai-coder — edit .ai-coder/Dockerfile to customize.",
    "",
    "FROM python:3.12-slim",
    "WORKDIR /app",
    "",
    "COPY requirements.txt* pyproject.toml* poetry.lock* ./",
    "RUN \\",
    "  if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; \\",
    "  elif [ -f pyproject.toml ]; then pip install --no-cache-dir . ; \\",
    "  fi",
    "",
    "COPY . .",
    "",
    ...(build ? [`RUN ${build}`, ""] : []),
    "ENV PORT=3000",
    "EXPOSE 3000",
    `CMD ["sh", "-c", "${start}"]`,
    "",
  ].join("\n")
}

function renderStatic(manifest: RunManifest): string {
  const start = escapeShell(manifest.start)
  return [
    "# Generated by ai-coder — edit .ai-coder/Dockerfile to customize.",
    "",
    "FROM node:22-alpine",
    "WORKDIR /app",
    "COPY . .",
    "",
    "ENV PORT=3000",
    "EXPOSE 3000",
    `CMD ["sh", "-c", "${start}"]`,
    "",
  ].join("\n")
}

function renderGeneric(manifest: RunManifest): string {
  const start = escapeShell(manifest.start)
  return [
    "# Generated by ai-coder — this is a minimal fallback.",
    "# Your stack didn't match a built-in template. Commit a real Dockerfile",
    "# at the repo root to take over.",
    "",
    "FROM debian:stable-slim",
    "WORKDIR /app",
    "COPY . .",
    "",
    "ENV PORT=3000",
    "EXPOSE 3000",
    `CMD ["sh", "-c", "${start}"]`,
    "",
  ].join("\n")
}

// Build a stable image tag for a given cwd. `sha1(cwd)` is overkill but
// keeps the tag safe for shell use and avoids leaking the path. We don't
// include the manifest in the hash — Docker's own layer cache handles that
// via Dockerfile+context diffing.
function buildImageTag(cwd: string): string {
  let h = 0
  for (let i = 0; i < cwd.length; i++) {
    h = (h * 31 + cwd.charCodeAt(i)) | 0
  }
  const suffix = Math.abs(h).toString(36)
  return `ai-coder:${suffix}`
}

function escapeShell(cmd: string): string {
  // Embedded in a JSON string ("sh", "-c", "...") — escape backslashes and
  // double-quotes. Single-quotes are fine because we're in double-quoted JSON.
  return cmd.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

async function exists(path: string): Promise<boolean> {
  try {
    await fsp.access(path)
    return true
  } catch {
    return false
  }
}

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await fsp.readFile(path, "utf8")
  } catch {
    return null
  }
}
